// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2017.4
// Copyright (C) 1986-2017 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

#ifndef _load_bigendian_HH_
#define _load_bigendian_HH_

#include "systemc.h"
#include "AESL_pkg.h"

#include "load_bigendian_BUS_A_s_axi.h"

namespace ap_rtl {

template<unsigned int C_S_AXI_BUS_A_ADDR_WIDTH = 5,
         unsigned int C_S_AXI_BUS_A_DATA_WIDTH = 32>
struct load_bigendian : public sc_module {
    // Port declarations 20
    sc_in< sc_logic > s_axi_BUS_A_AWVALID;
    sc_out< sc_logic > s_axi_BUS_A_AWREADY;
    sc_in< sc_uint<C_S_AXI_BUS_A_ADDR_WIDTH> > s_axi_BUS_A_AWADDR;
    sc_in< sc_logic > s_axi_BUS_A_WVALID;
    sc_out< sc_logic > s_axi_BUS_A_WREADY;
    sc_in< sc_uint<C_S_AXI_BUS_A_DATA_WIDTH> > s_axi_BUS_A_WDATA;
    sc_in< sc_uint<C_S_AXI_BUS_A_DATA_WIDTH/8> > s_axi_BUS_A_WSTRB;
    sc_in< sc_logic > s_axi_BUS_A_ARVALID;
    sc_out< sc_logic > s_axi_BUS_A_ARREADY;
    sc_in< sc_uint<C_S_AXI_BUS_A_ADDR_WIDTH> > s_axi_BUS_A_ARADDR;
    sc_out< sc_logic > s_axi_BUS_A_RVALID;
    sc_in< sc_logic > s_axi_BUS_A_RREADY;
    sc_out< sc_uint<C_S_AXI_BUS_A_DATA_WIDTH> > s_axi_BUS_A_RDATA;
    sc_out< sc_lv<2> > s_axi_BUS_A_RRESP;
    sc_out< sc_logic > s_axi_BUS_A_BVALID;
    sc_in< sc_logic > s_axi_BUS_A_BREADY;
    sc_out< sc_lv<2> > s_axi_BUS_A_BRESP;
    sc_in_clk ap_clk;
    sc_in< sc_logic > ap_rst_n;
    sc_out< sc_logic > interrupt;
    sc_signal< sc_logic > ap_var_for_const0;
    // Port declarations for the virtual clock. 
    sc_in_clk ap_virtual_clock;


    // Module declarations
    load_bigendian(sc_module_name name);
    SC_HAS_PROCESS(load_bigendian);

    ~load_bigendian();

    sc_trace_file* mVcdFile;

    ofstream mHdltvinHandle;
    ofstream mHdltvoutHandle;
    load_bigendian_BUS_A_s_axi<C_S_AXI_BUS_A_ADDR_WIDTH,C_S_AXI_BUS_A_DATA_WIDTH>* load_bigendian_BUS_A_s_axi_U;
    sc_signal< sc_logic > ap_start;
    sc_signal< sc_logic > ap_done;
    sc_signal< sc_logic > ap_idle;
    sc_signal< sc_logic > ap_ready;
    sc_signal< sc_lv<8> > x;
    sc_signal< sc_lv<8> > y;
    sc_signal< sc_logic > ap_rst_n_inv;
    static const sc_logic ap_const_logic_1;
    static const int C_S_AXI_DATA_WIDTH;
    static const sc_logic ap_const_logic_0;
    // Thread declarations
    void thread_ap_var_for_const0();
    void thread_ap_done();
    void thread_ap_idle();
    void thread_ap_ready();
    void thread_ap_rst_n_inv();
    void thread_hdltv_gen();
};

}

using namespace ap_rtl;

#endif
