// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2017.4
// Copyright (C) 1986-2017 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

#include "load_bigendian.h"
#include "AESL_pkg.h"

using namespace std;

namespace ap_rtl {

const sc_logic load_bigendian::ap_const_logic_1 = sc_dt::Log_1;
const int load_bigendian::C_S_AXI_DATA_WIDTH = "100000";
const sc_logic load_bigendian::ap_const_logic_0 = sc_dt::Log_0;

load_bigendian::load_bigendian(sc_module_name name) : sc_module(name), mVcdFile(0) {
    load_bigendian_BUS_A_s_axi_U = new load_bigendian_BUS_A_s_axi<C_S_AXI_BUS_A_ADDR_WIDTH,C_S_AXI_BUS_A_DATA_WIDTH>("load_bigendian_BUS_A_s_axi_U");
    load_bigendian_BUS_A_s_axi_U->AWVALID(s_axi_BUS_A_AWVALID);
    load_bigendian_BUS_A_s_axi_U->AWREADY(s_axi_BUS_A_AWREADY);
    load_bigendian_BUS_A_s_axi_U->AWADDR(s_axi_BUS_A_AWADDR);
    load_bigendian_BUS_A_s_axi_U->WVALID(s_axi_BUS_A_WVALID);
    load_bigendian_BUS_A_s_axi_U->WREADY(s_axi_BUS_A_WREADY);
    load_bigendian_BUS_A_s_axi_U->WDATA(s_axi_BUS_A_WDATA);
    load_bigendian_BUS_A_s_axi_U->WSTRB(s_axi_BUS_A_WSTRB);
    load_bigendian_BUS_A_s_axi_U->ARVALID(s_axi_BUS_A_ARVALID);
    load_bigendian_BUS_A_s_axi_U->ARREADY(s_axi_BUS_A_ARREADY);
    load_bigendian_BUS_A_s_axi_U->ARADDR(s_axi_BUS_A_ARADDR);
    load_bigendian_BUS_A_s_axi_U->RVALID(s_axi_BUS_A_RVALID);
    load_bigendian_BUS_A_s_axi_U->RREADY(s_axi_BUS_A_RREADY);
    load_bigendian_BUS_A_s_axi_U->RDATA(s_axi_BUS_A_RDATA);
    load_bigendian_BUS_A_s_axi_U->RRESP(s_axi_BUS_A_RRESP);
    load_bigendian_BUS_A_s_axi_U->BVALID(s_axi_BUS_A_BVALID);
    load_bigendian_BUS_A_s_axi_U->BREADY(s_axi_BUS_A_BREADY);
    load_bigendian_BUS_A_s_axi_U->BRESP(s_axi_BUS_A_BRESP);
    load_bigendian_BUS_A_s_axi_U->ACLK(ap_clk);
    load_bigendian_BUS_A_s_axi_U->ARESET(ap_rst_n_inv);
    load_bigendian_BUS_A_s_axi_U->ACLK_EN(ap_var_for_const0);
    load_bigendian_BUS_A_s_axi_U->ap_start(ap_start);
    load_bigendian_BUS_A_s_axi_U->interrupt(interrupt);
    load_bigendian_BUS_A_s_axi_U->ap_ready(ap_ready);
    load_bigendian_BUS_A_s_axi_U->ap_done(ap_done);
    load_bigendian_BUS_A_s_axi_U->ap_idle(ap_idle);
    load_bigendian_BUS_A_s_axi_U->x(x);
    load_bigendian_BUS_A_s_axi_U->y(y);

    SC_METHOD(thread_ap_done);
    sensitive << ( ap_start );

    SC_METHOD(thread_ap_idle);

    SC_METHOD(thread_ap_ready);
    sensitive << ( ap_start );

    SC_METHOD(thread_ap_rst_n_inv);
    sensitive << ( ap_rst_n );

    SC_THREAD(thread_hdltv_gen);
    sensitive << ( ap_virtual_clock.pos() );

    SC_THREAD(thread_ap_var_for_const0);

    static int apTFileNum = 0;
    stringstream apTFilenSS;
    apTFilenSS << "load_bigendian_sc_trace_" << apTFileNum ++;
    string apTFn = apTFilenSS.str();
    mVcdFile = sc_create_vcd_trace_file(apTFn.c_str());
    mVcdFile->set_time_unit(1, SC_PS);
    if (1) {
#ifdef __HLS_TRACE_LEVEL_PORT__
    sc_trace(mVcdFile, s_axi_BUS_A_AWVALID, "(port)s_axi_BUS_A_AWVALID");
    sc_trace(mVcdFile, s_axi_BUS_A_AWREADY, "(port)s_axi_BUS_A_AWREADY");
    sc_trace(mVcdFile, s_axi_BUS_A_AWADDR, "(port)s_axi_BUS_A_AWADDR");
    sc_trace(mVcdFile, s_axi_BUS_A_WVALID, "(port)s_axi_BUS_A_WVALID");
    sc_trace(mVcdFile, s_axi_BUS_A_WREADY, "(port)s_axi_BUS_A_WREADY");
    sc_trace(mVcdFile, s_axi_BUS_A_WDATA, "(port)s_axi_BUS_A_WDATA");
    sc_trace(mVcdFile, s_axi_BUS_A_WSTRB, "(port)s_axi_BUS_A_WSTRB");
    sc_trace(mVcdFile, s_axi_BUS_A_ARVALID, "(port)s_axi_BUS_A_ARVALID");
    sc_trace(mVcdFile, s_axi_BUS_A_ARREADY, "(port)s_axi_BUS_A_ARREADY");
    sc_trace(mVcdFile, s_axi_BUS_A_ARADDR, "(port)s_axi_BUS_A_ARADDR");
    sc_trace(mVcdFile, s_axi_BUS_A_RVALID, "(port)s_axi_BUS_A_RVALID");
    sc_trace(mVcdFile, s_axi_BUS_A_RREADY, "(port)s_axi_BUS_A_RREADY");
    sc_trace(mVcdFile, s_axi_BUS_A_RDATA, "(port)s_axi_BUS_A_RDATA");
    sc_trace(mVcdFile, s_axi_BUS_A_RRESP, "(port)s_axi_BUS_A_RRESP");
    sc_trace(mVcdFile, s_axi_BUS_A_BVALID, "(port)s_axi_BUS_A_BVALID");
    sc_trace(mVcdFile, s_axi_BUS_A_BREADY, "(port)s_axi_BUS_A_BREADY");
    sc_trace(mVcdFile, s_axi_BUS_A_BRESP, "(port)s_axi_BUS_A_BRESP");
    sc_trace(mVcdFile, ap_clk, "(port)ap_clk");
    sc_trace(mVcdFile, ap_rst_n, "(port)ap_rst_n");
    sc_trace(mVcdFile, interrupt, "(port)interrupt");
#endif
#ifdef __HLS_TRACE_LEVEL_INT__
    sc_trace(mVcdFile, ap_start, "ap_start");
    sc_trace(mVcdFile, ap_done, "ap_done");
    sc_trace(mVcdFile, ap_idle, "ap_idle");
    sc_trace(mVcdFile, ap_ready, "ap_ready");
    sc_trace(mVcdFile, x, "x");
    sc_trace(mVcdFile, y, "y");
    sc_trace(mVcdFile, ap_rst_n_inv, "ap_rst_n_inv");
#endif

    }
    mHdltvinHandle.open("load_bigendian.hdltvin.dat");
    mHdltvoutHandle.open("load_bigendian.hdltvout.dat");
}

load_bigendian::~load_bigendian() {
    if (mVcdFile) 
        sc_close_vcd_trace_file(mVcdFile);

    mHdltvinHandle << "] " << endl;
    mHdltvoutHandle << "] " << endl;
    mHdltvinHandle.close();
    mHdltvoutHandle.close();
    delete load_bigendian_BUS_A_s_axi_U;
}

void load_bigendian::thread_ap_var_for_const0() {
    ap_var_for_const0 = ap_const_logic_1;
}

void load_bigendian::thread_ap_done() {
    ap_done = ap_start.read();
}

void load_bigendian::thread_ap_idle() {
    ap_idle = ap_const_logic_1;
}

void load_bigendian::thread_ap_ready() {
    ap_ready = ap_start.read();
}

void load_bigendian::thread_ap_rst_n_inv() {
    ap_rst_n_inv =  (sc_logic) (~ap_rst_n.read());
}

void load_bigendian::thread_hdltv_gen() {
    const char* dump_tv = std::getenv("AP_WRITE_TV");
    if (!(dump_tv && string(dump_tv) == "on")) return;

    wait();

    mHdltvinHandle << "[ " << endl;
    mHdltvoutHandle << "[ " << endl;
    int ap_cycleNo = 0;
    while (1) {
        wait();
        const char* mComma = ap_cycleNo == 0 ? " " : ", " ;
        mHdltvinHandle << mComma << "{"  <<  " \"s_axi_BUS_A_AWVALID\" :  \"" << s_axi_BUS_A_AWVALID.read() << "\" ";
        mHdltvoutHandle << mComma << "{"  <<  " \"s_axi_BUS_A_AWREADY\" :  \"" << s_axi_BUS_A_AWREADY.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"s_axi_BUS_A_AWADDR\" :  \"" << s_axi_BUS_A_AWADDR.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"s_axi_BUS_A_WVALID\" :  \"" << s_axi_BUS_A_WVALID.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"s_axi_BUS_A_WREADY\" :  \"" << s_axi_BUS_A_WREADY.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"s_axi_BUS_A_WDATA\" :  \"" << s_axi_BUS_A_WDATA.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"s_axi_BUS_A_WSTRB\" :  \"" << s_axi_BUS_A_WSTRB.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"s_axi_BUS_A_ARVALID\" :  \"" << s_axi_BUS_A_ARVALID.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"s_axi_BUS_A_ARREADY\" :  \"" << s_axi_BUS_A_ARREADY.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"s_axi_BUS_A_ARADDR\" :  \"" << s_axi_BUS_A_ARADDR.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"s_axi_BUS_A_RVALID\" :  \"" << s_axi_BUS_A_RVALID.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"s_axi_BUS_A_RREADY\" :  \"" << s_axi_BUS_A_RREADY.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"s_axi_BUS_A_RDATA\" :  \"" << s_axi_BUS_A_RDATA.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"s_axi_BUS_A_RRESP\" :  \"" << s_axi_BUS_A_RRESP.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"s_axi_BUS_A_BVALID\" :  \"" << s_axi_BUS_A_BVALID.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"s_axi_BUS_A_BREADY\" :  \"" << s_axi_BUS_A_BREADY.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"s_axi_BUS_A_BRESP\" :  \"" << s_axi_BUS_A_BRESP.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"ap_rst_n\" :  \"" << ap_rst_n.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"interrupt\" :  \"" << interrupt.read() << "\" ";
        mHdltvinHandle << "}" << std::endl;
        mHdltvoutHandle << "}" << std::endl;
        ap_cycleNo++;
    }
}

}

