// ==============================================================
// File generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2017.4
// Copyright (C) 1986-2017 Xilinx, Inc. All Rights Reserved.
// 
// ==============================================================

#ifndef __linux__

#include "xstatus.h"
#include "xparameters.h"
#include "xload_bigendian.h"

extern XLoad_bigendian_Config XLoad_bigendian_ConfigTable[];

XLoad_bigendian_Config *XLoad_bigendian_LookupConfig(u16 DeviceId) {
	XLoad_bigendian_Config *ConfigPtr = NULL;

	int Index;

	for (Index = 0; Index < XPAR_XLOAD_BIGENDIAN_NUM_INSTANCES; Index++) {
		if (XLoad_bigendian_ConfigTable[Index].DeviceId == DeviceId) {
			ConfigPtr = &XLoad_bigendian_ConfigTable[Index];
			break;
		}
	}

	return ConfigPtr;
}

int XLoad_bigendian_Initialize(XLoad_bigendian *InstancePtr, u16 DeviceId) {
	XLoad_bigendian_Config *ConfigPtr;

	Xil_AssertNonvoid(InstancePtr != NULL);

	ConfigPtr = XLoad_bigendian_LookupConfig(DeviceId);
	if (ConfigPtr == NULL) {
		InstancePtr->IsReady = 0;
		return (XST_DEVICE_NOT_FOUND);
	}

	return XLoad_bigendian_CfgInitialize(InstancePtr, ConfigPtr);
}

#endif

