// ==============================================================
// File generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2017.4
// Copyright (C) 1986-2017 Xilinx, Inc. All Rights Reserved.
// 
// ==============================================================

/***************************** Include Files *********************************/
#include "xload_bigendian.h"

/************************** Function Implementation *************************/
#ifndef __linux__
int XLoad_bigendian_CfgInitialize(XLoad_bigendian *InstancePtr, XLoad_bigendian_Config *ConfigPtr) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(ConfigPtr != NULL);

    InstancePtr->Bus_a_BaseAddress = ConfigPtr->Bus_a_BaseAddress;
    InstancePtr->IsReady = XIL_COMPONENT_IS_READY;

    return XST_SUCCESS;
}
#endif

void XLoad_bigendian_Start(XLoad_bigendian *InstancePtr) {
    u32 Data;

    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XLoad_bigendian_ReadReg(InstancePtr->Bus_a_BaseAddress, XLOAD_BIGENDIAN_BUS_A_ADDR_AP_CTRL) & 0x80;
    XLoad_bigendian_WriteReg(InstancePtr->Bus_a_BaseAddress, XLOAD_BIGENDIAN_BUS_A_ADDR_AP_CTRL, Data | 0x01);
}

u32 XLoad_bigendian_IsDone(XLoad_bigendian *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XLoad_bigendian_ReadReg(InstancePtr->Bus_a_BaseAddress, XLOAD_BIGENDIAN_BUS_A_ADDR_AP_CTRL);
    return (Data >> 1) & 0x1;
}

u32 XLoad_bigendian_IsIdle(XLoad_bigendian *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XLoad_bigendian_ReadReg(InstancePtr->Bus_a_BaseAddress, XLOAD_BIGENDIAN_BUS_A_ADDR_AP_CTRL);
    return (Data >> 2) & 0x1;
}

u32 XLoad_bigendian_IsReady(XLoad_bigendian *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XLoad_bigendian_ReadReg(InstancePtr->Bus_a_BaseAddress, XLOAD_BIGENDIAN_BUS_A_ADDR_AP_CTRL);
    // check ap_start to see if the pcore is ready for next input
    return !(Data & 0x1);
}

void XLoad_bigendian_EnableAutoRestart(XLoad_bigendian *InstancePtr) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XLoad_bigendian_WriteReg(InstancePtr->Bus_a_BaseAddress, XLOAD_BIGENDIAN_BUS_A_ADDR_AP_CTRL, 0x80);
}

void XLoad_bigendian_DisableAutoRestart(XLoad_bigendian *InstancePtr) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XLoad_bigendian_WriteReg(InstancePtr->Bus_a_BaseAddress, XLOAD_BIGENDIAN_BUS_A_ADDR_AP_CTRL, 0);
}

void XLoad_bigendian_Set_x(XLoad_bigendian *InstancePtr, u32 Data) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XLoad_bigendian_WriteReg(InstancePtr->Bus_a_BaseAddress, XLOAD_BIGENDIAN_BUS_A_ADDR_X_DATA, Data);
}

u32 XLoad_bigendian_Get_x(XLoad_bigendian *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XLoad_bigendian_ReadReg(InstancePtr->Bus_a_BaseAddress, XLOAD_BIGENDIAN_BUS_A_ADDR_X_DATA);
    return Data;
}

void XLoad_bigendian_Set_y(XLoad_bigendian *InstancePtr, u32 Data) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XLoad_bigendian_WriteReg(InstancePtr->Bus_a_BaseAddress, XLOAD_BIGENDIAN_BUS_A_ADDR_Y_DATA, Data);
}

u32 XLoad_bigendian_Get_y(XLoad_bigendian *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XLoad_bigendian_ReadReg(InstancePtr->Bus_a_BaseAddress, XLOAD_BIGENDIAN_BUS_A_ADDR_Y_DATA);
    return Data;
}

void XLoad_bigendian_InterruptGlobalEnable(XLoad_bigendian *InstancePtr) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XLoad_bigendian_WriteReg(InstancePtr->Bus_a_BaseAddress, XLOAD_BIGENDIAN_BUS_A_ADDR_GIE, 1);
}

void XLoad_bigendian_InterruptGlobalDisable(XLoad_bigendian *InstancePtr) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XLoad_bigendian_WriteReg(InstancePtr->Bus_a_BaseAddress, XLOAD_BIGENDIAN_BUS_A_ADDR_GIE, 0);
}

void XLoad_bigendian_InterruptEnable(XLoad_bigendian *InstancePtr, u32 Mask) {
    u32 Register;

    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Register =  XLoad_bigendian_ReadReg(InstancePtr->Bus_a_BaseAddress, XLOAD_BIGENDIAN_BUS_A_ADDR_IER);
    XLoad_bigendian_WriteReg(InstancePtr->Bus_a_BaseAddress, XLOAD_BIGENDIAN_BUS_A_ADDR_IER, Register | Mask);
}

void XLoad_bigendian_InterruptDisable(XLoad_bigendian *InstancePtr, u32 Mask) {
    u32 Register;

    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Register =  XLoad_bigendian_ReadReg(InstancePtr->Bus_a_BaseAddress, XLOAD_BIGENDIAN_BUS_A_ADDR_IER);
    XLoad_bigendian_WriteReg(InstancePtr->Bus_a_BaseAddress, XLOAD_BIGENDIAN_BUS_A_ADDR_IER, Register & (~Mask));
}

void XLoad_bigendian_InterruptClear(XLoad_bigendian *InstancePtr, u32 Mask) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XLoad_bigendian_WriteReg(InstancePtr->Bus_a_BaseAddress, XLOAD_BIGENDIAN_BUS_A_ADDR_ISR, Mask);
}

u32 XLoad_bigendian_InterruptGetEnabled(XLoad_bigendian *InstancePtr) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    return XLoad_bigendian_ReadReg(InstancePtr->Bus_a_BaseAddress, XLOAD_BIGENDIAN_BUS_A_ADDR_IER);
}

u32 XLoad_bigendian_InterruptGetStatus(XLoad_bigendian *InstancePtr) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    return XLoad_bigendian_ReadReg(InstancePtr->Bus_a_BaseAddress, XLOAD_BIGENDIAN_BUS_A_ADDR_ISR);
}

